### ISSUE TITLE
Unable to add wallet

### ISSUE THREAD

**Issue by Jeezman** [Zero-1729/volt#7]
### screenshot
<img width="481" alt="Screenshot 2024-06-07 at 16 51 53" src="https://github.com/Zero-1729/volt/assets/8108245/475bf0de-e04c-4121-aa2c-8e4955706311">

### Error message on terminal
```
 LOG  [Error Catch]  [Error: Error: Could not parse descriptor tr(xprv9zC8agyvKuyfJ6iGFaaLNpTtjjQambiGfSnRzF2vX59V1veWQB8ZxzHRBMoEpbdjZgFjjJQUMwSXzQ7XZmr5v8n4nin5hPRRmgb4fXHyYJe/86'/0'/0'/0/*)]

 ERROR  [AsyncStorage] (Add wallet) Error loading data: Error: Could not parse descriptor
```

I think the error is as a result of the default account being set to `unified` ie `Lightning (BIP86)`

**Comment by Zero-1729** [comment]
This is due to the descriptor library, [bitcoinerlab/descriptors](https://github.com/bitcoinerlab/descriptors), I believe. Volt currently requires a patch which enables it to parse taproot descriptors (`tr()`) using the library. The proper fix is for the [patch](https://github.com/bitcoinerlab/descriptors/pull/24) I have opened to be merged upstream.

For now, manually editing the files in the PR for the bitcoinerlab/descriptors in the `node_modules` should resolve this problem. Hope this helps.

**Comment by Jeezman** [comment]
> This is due to the descriptor library, [bitcoinerlab/descriptors](https://github.com/bitcoinerlab/descriptors), I believe. Volt currently requires a patch which enables it to parse taproot descriptors (`tr()`) using the library. The proper fix is for the [patch](https://github.com/bitcoinerlab/descriptors/pull/24) I have opened to be merged upstream.
> 
> For now, manually editing the files in the PR for the bitcoinerlab/descriptors in the `node_modules` should resolve this problem. Hope this helps.

Got it. Thoughts on building your fork and adding it as the dependency url?
```
"@bitcoinerlab/descriptors": "https://github.com/Zero-1729/descriptors.git",
```
I forked and built your patch on a personal repo and it worked. Lmk what you think

**Comment by Zero-1729** [comment]
Yeah, fair enough, just switched to my fork for the time being; will be part of the next tagged release (`v0.4.4-beta.1`).

Will revert back to the upstram repo once the PR has been merged.
